### ISSUE TITLE
"Attempt to Compare with a nil number" When Trying to place a trader: init.lua line 333

### ISSUE THREAD

**Issue by Routhinator** [Sokomine/mobf_trader#1]
```
An unhandled exception occurred: ...e/minetest/minetest/bin/../mods/mobf_trader/init.lua:333: attempt to compare nil with number
```

This occurs whenever I try to place a trader mob. I can use the '/trader' command... however if I run clearobjects and try to replace the mob, this occurs.

**Comment by Routhinator** [comment]
The mobf_trader object was being redeclared in mob_basics.lua

Pull request #2 addresses and fixes this bug.

**Comment by Sokomine** [comment]
The pull request has been merged. However, some of these files might also be of intrest for other mob mods where the mobf_trader varialbe is not defined. I've made it better compatible now.
